name: Run Selenium Pytest

# on: [push, pull_request]
on:
  push:
    branches: [master,main]
  pull_request:
    branches: [master,main]
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pytest selenium

    - name: Run tests
      run: |
        pytest -v --maxfail=1 --disable-warnings
