  name: Run Selenium Pytest and Locust
  on:
    push:
      branches: [main,locust-trigger,master]  # ทุก branch ที่ขึ้นต้นด้วย feature/
    pull_request:
      branches: [main]
  
  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
      # เช็คเอา repository ของเรามา
      - uses: actions/checkout@v3

  # ติดตั้ง Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # เลือกเวอร์ชัน Python
  # ติดตั้ง dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium locust
  # รัน pytest
      - name: Run tests
        run: |
          pytest -v --maxfail=1 --disable-warnings
        #ถ้าไฟล์อยู่ใน subfolder ให้เพิ่ม path ในคำสั่ง run: pytest tests/ -v --maxfail=1 --disable-warnings
        #locust -f locustfile.py --headless -u 10 -r 1 --run-time 1m  
        #-u = จำนวน user, -r = spawn rate, --run-time = ระยะเวลา run

