name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium locust

      - name: Run Pytest (Selenium tests)
        run: |
          pytest -v --maxfail=1 --disable-warnings

      - name: Run Locust (headless load test)
        run: |
          locust -f test_locustfile.py --headless -u 5 -r 1 -t 10s
