name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install pytest selenium locust
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          driver = webdriver.Chrome(executable_path="/usr/bin/chromedriver", options=options)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium locust

      - name: Run Pytest (Selenium tests)
        run: |
          pytest -v --maxfail=1 --disable-warnings

      - name: Run Locust (headless load test)
        run: |
          locust -f test_locustfile.py --headless -u 5 -r 1 -t 10s
